In [16]:
import pandas as pd
import sqlite3 
import os

## Importação dos Dados

In [14]:
 df_padrao = pd.read_csv("DADOS_PROJETO/Data/Data/Escolas/escolas122023.csv", sep=";", encoding='latin1')

In [25]:
columns_padrao = df_padrao.columns
diretorio_escola = "DADOS_PROJETO/Data/Data/Escolas"
arquivo_csv_escolas = os.listdir(diretorio_escola)

In [36]:
lista_dataframe = []
for arquivo in arquivo_csv_escolas:
    if '.csv' in arquivo:
        caminho_completo = diretorio_escola + '/' + arquivo
        df = pd.read_csv(caminho_completo, names= columns_padrao, header= None, sep=";", encoding='latin1', skiprows=1) 
        lista_dataframe.append(df)
    else:
        continue

In [50]:
lista_dataframe = []
for arquivo in arquivo_csv_escolas:
    if '.csv' in arquivo:
        caminho_completo = diretorio_escola + '/' + arquivo
        df = pd.read_csv(caminho_completo, names=columns_padrao, header=None, sep=";", encoding='latin1', skiprows=1)
        lista_dataframe.append(df)
    else:
        continue

# Resetando os índices de cada DataFrame
lista_dataframe = [df.reset_index(drop=True) for df in lista_dataframe]

# Concatenando os DataFrames
# Concatenando os DataFrames
df_final = pd.concat(lista_dataframe, ignore_index=True)

In [51]:
lista_dataframe[11]

,DRE,CODESC,TIPOESC,NOMES,DESLOC,CEU,DIRETORIA,SUBPREF,ENDERECO,NUMERO,...,ATO_CRIACAO,DOM_CRIACAO,DT_INI_CONV,DT_AUTORIZA,DT_EXTINCAO,FX_ETARIA.1,NOME_ANT,LATITUDE,LONGITUDE,DATABASE
0,G,86,EMEI,PAULO CAMILHIER FLORENCANO,PAULO CAMILHIER FLORENCANO,NaN,GUAIANASES,GUAIANASES,RUA FELICIANO DE MENDONCA,502,...,26.134,13/06/1988,NaN,16/03/1991,NaN,NaN,NaN,-23553905,-46398452,25/12/2023
1,FO,94,EMEI,VICENTE PAULO DA SILVA,VICENTE PAULO DA SILVA,NaN,FREGUESIA/BRASILANDIA,CASA VERDE/CACHOEIRINHA,RUA DOUTOR FLEURY SILVEIRA,295,...,26.314,04/07/1988,NaN,16/03/1991,NaN,NaN,NaN,-23489728,-46670198,25/12/2023
2,MP,108,EMEF,"JOSE ERMIRIO DE MORAES, SEN.","JOSE ERMIRIO DE MORAES, SEN.",NaN,SAO MIGUEL,SAO MIGUEL,RUA SAO BRAS DO SUACUI,159,...,26.312,05/07/1988,NaN,13/03/2001,NaN,NaN,VILA NITRO OPERARIA,-23478312,-46427344,25/12/2023
3,BT,191,EMEF,"ALIPIO CORREA NETO, PROF.","ALIPIO CORREA NETO, PROF.",NaN,BUTANTA,BUTANTA,AVENIDA JOAO CAIAFFA,140,...,26.003,27/05/1988,NaN,16/03/1991,NaN,NaN,NaN,-23612237,-46749888,25/12/2023
4,PJ,205,EMEBS,"VERA LUCIA APARECIDA RIBEIRO, PROFA.","VERA LUCIA APARECIDA RIBEIRO, PROFA.",NaN,PIRITUBA,PIRITUBA,RUA BENEDITO PEREIRA,206,...,26.229,22/06/1988,NaN,16/03/1991,NaN,NaN,NaN,-23486142,-46733901,25/12/2023
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4926,SM,700041,CEU AT COM,SAO RAFAEL,SAO RAFAEL,SAO RAFAEL,SAO MATEUS,SAO MATEUS,RUA CINIRA POLÔNIO,100,...,99999999999999999999,18/05/2011,NaN,NaN,NaN,NaN,NaN,-23620144,-46456550,25/12/2023
4927,SM,700042,CEU AT COM,ROSA DA CHINA,ROSA DA CHINA,ROSA DA CHINA,SAO MATEUS,SAPOPEMBA,RUA CLARA PETRELA,113,...,99999999999999999999,18/05/2011,NaN,NaN,NaN,NaN,NaN,-23621567,-46500775,25/12/2023
4928,SM,700043,CEU AT COM,SAPOPEMBA,SAPOPEMBA,SAPOPEMBA,SAO MATEUS,SAPOPEMBA,RUA MANUEL QUIRINO DE MATTOS,S/N,...,99999999999999999999,18/05/2011,NaN,NaN,NaN,NaN,NaN,-23609804,-46494006,25/12/2023
4929,SM,700044,CEU AT COM,"ALTO ALEGRE - PAULO SUYOSH MINAMI, PROF.","ALTO ALEGRE - PAULO SUYOSH MINAMI, PROF.",ALTO ALEGRE,SAO MATEUS,SAO MATEUS,AVENIDA BENTO GUELFI,S/N,...,99999999999999999999,18/05/2011,NaN,NaN,NaN,NaN,ALTO ALEGRE,-23609738,-46426886,25/12/2023
4930,IP,700045,CEU AT COM,"HELIOPOLIS - ARLETE PERSOLI, PROFA","HELIOPOLIS - ARLETE PERSOLI, PROFA",HELIOPOLIS,IPIRANGA,IPIRANGA,ESTRADA DAS LÁGRIMAS,2385,...,1,07/03/2016,NaN,NaN,NaN,NaN,NaN,-23622172,-46590795,25/12/2023

In [54]:
df_final = pd.concat(lista_dataframe, ignore_index= True)
df_final.to_excel('teste_1.xlsx')